import { Link } from 'react-router-dom'
import { lessons, macroUnits } from '../data/course'
import { useStudy } from '../state/StudyContext'
import { DecorativeCloud, DecorativeHeart, DecorativeSparkle } from '../components/Decorations'
import { ProgressBar } from '../components/ProgressBar'

export function Dashboard() {
  const { progress, courseCompletion, mastery, settings, setExamDate } = useStudy()
  const next = lessons.find((lesson) => !progress.completedLessons.includes(lesson.id)) ?? lessons[0]
  const examDays = settings.examDate ? Math.max(0, Math.ceil((new Date(settings.examDate).getTime() - Date.now()) / 86400000)) : null
  const availableMinutes = macroUnits.filter((u) => u.available).reduce((sum,u) => sum+u.estimatedMinutes,0)
  return <div className="dashboard page"><section className="hero"><div className="hero-copy"><span className="eyebrow">Missione di oggi · slancio attivo</span><h1>Costruiamo una risposta<br/><em>che regge all’orale.</em></h1><p>Un nodo alla volta: capisci la struttura, fai un check rapido, poi trasformala in voce.</p><div className="hero-actions"><Link className="primary-button" to={`/lezione/${next?.id}`}>Continua · {next?.title} <span>→</span></Link><Link className="text-link" to="/percorso">Vedi il percorso</Link></div><div className="hero-meta"><span><b>{next?.estimatedMinutes ?? 0}</b> min nella prossima sessione</span><span><b>{next?.sections.length ?? 0}</b> micro-obiettivi</span><span><b>1</b> checkpoint</span></div></div><div className="hero-visual"><DecorativeCloud className="cloud cloud-one"/><DecorativeCloud className="cloud cloud-two"/><div className="orbit"><div className="hero-ring"><span>{courseCompletion}%</span><small>corso</small></div><span className="orbit-dot dot-pink">理解</span><span className="orbit-dot dot-red">記憶</span><span className="orbit-dot dot-violet">接続</span></div><DecorativeHeart className="hero-heart"/><DecorativeSparkle className="hero-sparkle"/></div></section>
  <section className="metrics"><div><span className="metric-icon pink">◆</span><p><small>Copertura programma</small><strong>{courseCompletion}%</strong></p><ProgressBar value={courseCompletion} label="Copertura" compact/></div><div><span className="metric-icon violet">✦</span><p><small>Padronanza quiz</small><strong>{mastery}%</strong></p><ProgressBar value={mastery} label="Padronanza" compact/></div><div><span className="metric-icon red">◉</span><p><small>Prontezza orale</small><strong>{progress.oralReady.length}/7</strong></p><ProgressBar value={Math.round(progress.oralReady.length/7*100)} label="Orale" compact/></div></section>
  <div className="dashboard-grid"><section className="panel today-panel"><div className="panel-head"><div><span className="eyebrow">Sequenza consigliata</span><h2>I prossimi aha moment</h2></div><Link to="/percorso">Tutto il percorso →</Link></div><div className="mission-list">{lessons.slice(0,4).map((lesson,i) => <Link to={`/lezione/${lesson.id}`} key={lesson.id} className={progress.completedLessons.includes(lesson.id) ? 'done' : ''}><span className="mission-number">{progress.completedLessons.includes(lesson.id) ? '✓' : i+1}</span><span><strong>{lesson.title}</strong><small>{lesson.objectives[0]}</small></span><span className="mission-time">{lesson.estimatedMinutes} min</span></Link>)}</div></section>
  <aside className="panel exam-card"><span className="eyebrow">Conto alla rovescia</span><h2>{examDays === null ? 'Quando sarà l’esame?' : examDays === 0 ? 'Oggi è il giorno.' : `${examDays} giorni`}</h2><p>{examDays === null ? 'Imposta la data: il piano si adegua senza giudicarti.' : `Hai ${availableMinutes} minuti di percorso già attivo.`}</p><input aria-label="Data dell’esame" type="date" value={settings.examDate ?? ''} onChange={(event) => setExamDate(event.target.value)}/><Link className="secondary-button" to="/piano-48h">Apri piano 48 ore</Link></aside></div>
  <section className="unit-strip"><div className="panel-head"><div><span className="eyebrow">Mappa del corso</span><h2>12 blocchi, una storia connessa</h2></div></div><div className="unit-cards">{macroUnits.slice(0,5).map((unit) => <article key={unit.id} className={!unit.available ? 'locked' : ''}><span>0{unit.number}</span><h3>{unit.shortTitle}</h3><p>{unit.description}</p>{unit.available ? <Link to={`/percorso#${unit.id}`}>Esplora →</Link> : <small>Roadmap successiva</small>}</article>)}</div></section></div>
}
