import { useRef, type ChangeEvent } from 'react'
import { useStudy } from '../state/StudyContext'

export function SettingsPage() {
  const study = useStudy(); const input = useRef<HTMLInputElement>(null)
  const exportData = () => { const blob = new Blob([JSON.stringify({ progress: study.progress, settings: study.settings },null,2)],{type:'application/json'}); const link = document.createElement('a'); link.href=URL.createObjectURL(blob); link.download='kokoro-progressi.json'; link.click(); URL.revokeObjectURL(link.href) }
  const importData = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { try { study.importState(JSON.parse(String(reader.result))) } catch { window.alert('Il file non è un backup Kokoro valido.') } }; reader.readAsText(file) }
  return <div className="page narrow-page"><header className="page-heading"><span className="eyebrow">Impostazioni locali</span><h1>I tuoi dati restano qui</h1><p>Progressi e preferenze sono salvati nel browser. Esporta un backup quando vuoi.</p></header><section className="settings-panel"><div><span><strong>Tema</strong><small>Stessa identità, luce diversa.</small></span><button onClick={() => study.setTheme(study.settings.theme === 'light' ? 'dark' : 'light')}>{study.settings.theme === 'light' ? 'Passa a scuro' : 'Passa a chiaro'}</button></div><div><span><strong>Animazioni</strong><small>Scegli quanta motion usare senza perdere informazioni.</small></span><div className="motion-settings" role="group" aria-label="Intensità animazioni">{(['full','reduced','off'] as const).map((mode)=><button className={study.settings.motion===mode?'active':''} key={mode} onClick={()=>study.setMotion(mode)}>{mode==='full'?'Complete':mode==='reduced'?'Ridotte':'Disattivate'}</button>)}</div></div><div><span><strong>Backup progressi</strong><small>File JSON portabile e leggibile.</small></span><button onClick={exportData}>Esporta</button></div><div><span><strong>Ripristina backup</strong><small>Importa un file Kokoro precedente.</small></span><button onClick={() => input.current?.click()}>Importa</button><input ref={input} type="file" accept="application/json" hidden onChange={importData}/></div><div className="danger-setting"><span><strong>Ricominciamo</strong><small>Cancella progressi e tentativi locali.</small></span><button onClick={() => { if (window.confirm('Cancellare tutti i progressi locali?')) study.reset() }}>Reset</button></div></section></div>
}
